# Generated by Django 4.1.3 on 2022-11-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econnection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='date_of_application',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='date_of_approval',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='connection',
            name='modified_date',
            field=models.DateField(),
        ),
    ]
