# Generated by Django 4.1.3 on 2022-11-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econnection', '0002_alter_connection_date_of_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='date_of_approval',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='modified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
