# Generated by Django 4.1.3 on 2022-11-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econnection', '0003_alter_connection_date_of_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='pincode',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
