# Generated by Django 4.1.3 on 2022-11-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econnection', '0004_connection_pincode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ('-date_of_application',), 'verbose_name': 'Connection', 'verbose_name_plural': 'Connections'},
        ),
        migrations.AlterField(
            model_name='connection',
            name='reviewer_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='reviewer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('APR', 'Approved'), ('PE', 'Pending'), ('CONR', 'Connection Released'), ('RE', 'Rejected')], default='PE', max_length=10),
        ),
    ]
