# Generated by Django 4.1.3 on 2022-11-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econnection', '0006_alter_connection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(blank=True, choices=[('APR', 'Approved'), ('PE', 'Pending'), ('CONR', 'Connection Released'), ('RE', 'Rejected')], default='PE', max_length=10, null=True),
        ),
    ]
